# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='storeItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=10)),
                ('sku', models.CharField(max_length=20, unique=True)),
                ('image', django_resized.forms.ResizedImageField(upload_to='items/', verbose_name=[500, 300])),
                ('shortdesc', models.CharField(max_length=30)),
                ('longdesc', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spec', models.CharField(max_length=50)),
                ('dateAdded', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('dateAdded',),
            },
        ),
        migrations.AddField(
            model_name='specs',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.storeItems'),
        ),
    ]
