# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='totalprice',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
